version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - pandoc
  commands:
    - pip install uv
    - uv tool install tox --with tox-uv
    - tox run -e docs --notest
    - tox run -e docs --skip-pkg-install