version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - pandoc
  commands:
    - pip install uv
    - uv venv
    - uv pip install tox tox-uv
    - uv run tox -e docs $READTHEDOCS_OUTPUT/html